name       : libgda
version    : 5.2.10
release    : 20
source     :
    - https://download.gnome.org/sources/libgda/5.2/libgda-5.2.10.tar.xz : 6f6cdf7b8053f553b907e0c88a6064eb48cf2751852eb24323dcf027792334c8
homepage   : https://gitlab.gnome.org/GNOME/libgda
license    : GPL-2.0-only
component  : programming.library
summary    : A database access library
description: |
    Libgda is a (relatively small) database access library: it is a wrapper like ODBC but with more features to access several database engines.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(mariadb)
    - pkgconfig(libpq)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - itstool
    - libgcrypt-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-MySQL-8-Fix-compilation.patch
    %patch -p1 < $pkgfiles/0001-Revert-MySQL-adding-support-for-version-8-API.patch
    # Adapted from Fedora's monkeypatch of AUTHORS - rewrite all source files in
    # place and force utf8...
    for i in `find . -name "*.c" -or -name "*.h" -or -name "*.c.in" -or -name "*.h.in"` ; do
        iconv --from=ISO-8859-1 --to=UTF-8 $i > $i.new && \
        touch -r $i $i.new && mv $i.new $i
    done
    %configure --disable-static --disable-tools --enable-system-sqlite
build      : |
    %make
install    : |
    %make_install
