name       : libgda
version    : 5.2.4
release    : 5
source     :
    - https://download.gnome.org/sources/libgda/5.2/libgda-5.2.4.tar.xz : 2cee38dd583ccbaa5bdf6c01ca5f88cc08758b9b144938a51a478eb2684b765e
license    : GPL-2.0-only
component  : programming.library
summary    : A database access library
description: |
    Libgda is a (relatively small) database access library: it is a wrapper like ODBC but with more features to access several database engines.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(goocanvas-2.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libgvc)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Convert-files-to-Unicode.patch
    %patch -p1 < $pkgfiles/glib-2.54-ftbfs.patch
    # Adapted from Fedora's monkeypatch of AUTHORS - rewrite all source files in
    # place and force utf8...
    for i in `find . -name "*.c" -or -name "*.h" -or -name "*.c.in" -or -name "*.h.in"` ; do
        iconv --from=ISO-8859-1 --to=UTF-8 $i > $i.new && \
        touch -r $i $i.new && mv $i.new $i
    done
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
