name       : libgda
version    : 5.2.4
release    : 2
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libgda/5.2/libgda-5.2.4.tar.xz : 2cee38dd583ccbaa5bdf6c01ca5f88cc08758b9b144938a51a478eb2684b765e
license    : GPL-2.0
component  : programming
summary    : A database access library
description: |
    Libgda is a (relatively small) database access library: it is a wrapper like ODBC but with more features to access several database engines.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(goocanvas-2.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libgvc)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
